language: java

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify